FROM python:3.10
USER root
ADD requirements.txt /fed-flow/
#RUN apk add libc6-compat
#RUN apk add --no-cache git gcc mariadb-dev musl-dev linux-headers
#RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
#RUN pip install --upgrade pip
RUN pip install retry
COPY fedflow-env/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
#RUN pip uninstall numpy -y
#RUN pip install numpy==1.22.4
COPY app /fed-flow/app
COPY energy-estimation /fed-flow/energy
WORKDIR /fed-flow/