FROM python:3.10
USER root
#RUN apt update
#RUN apt install python3 python3-pip -y
ADD requirements.txt /fed-flow/
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install requests
#COPY fedflow-env/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY comm.py /fed-flow/
#COPY app /fed-flow/app
COPY energy-estimation /fed-flow/energy-estimation
#COPY energy.sh /fed-flow/
WORKDIR /fed-flow/
#ENTRYPOINT ["/bin/sh"]
#CMD ["energy.sh"]
